#!/bin/bash

if [ "$1" = "stop" ]; then
    pkill -f "gunicorn -w 3 -b 127.0.0.1:5005"
    exit 0
fi

cd /home/$USER/w/FMhost
source venv/bin/activate
cd app  
gunicorn -w 3 -b 127.0.0.1:5005 main:app
