#!/bin/bash


sudo firewall-cmd --permanent --add-service=http
sudo firewall-cmd --reload

echo "Firewall configured [ OK ]"

echo "Start Your Video Hosting ..."

cd app 

gunicorn -w 3 -b 127.0.0.1:5005 main:app



